### ISSUE TITLE
what type of programs are we supposed to add ?

### ISSUE THREAD

**Issue by Veershah26** [HackClubNUV/Python-50-Exercises#2]

**Comment by nimit2801** [comment]
Please, elaborate thank you.
@Veershah26

**Comment by Veershah26** [comment]
Like, should we follow a specific genre, like the practice1.py is a number guessing game, so are all the programs supposed to be games incorporating different concepts, or a different type of example file is welcome ?

**Comment by nimit2801** [comment]
Good question, I would like you to follow this thread: #1 for more details on what the project means to do.
This project does not have a Readme and will have soon. I guess that will answer your question.


If this answer solves your question please close this issue.
Thank you  @Veershah26
